### PR TITLE
assert() -> doAssert()

### PR DESCRIPTION
**Pull request by stefantalpalaru**

### CODE REVIEW

**Comment by zah** [comment]
This is compile-time code, so it doesn't need the usual treatment.

**Comment by stefantalpalaru** [comment]
Everything needs the usual treatment, so we can grep for "\bassert\b" instead of spending time to check if exceptions apply in particular cases.

**Comment by zah** [comment]
We stopped using this library some time ago btw. The code discussed here has been moved to `std_shims` where I assume you've already applied the change.

**Comment by stefantalpalaru** [comment]
```text
vendor/nim-eth/eth.nimble:14:         "package_visible_types",
vendor/nim-eth/eth/p2p/private/p2p_types.nim:3:  package_visible_types,
vendor/nim-eth/eth/p2p/rlpx_protocols/les/private/les_types.nim:3:  package_visible_types,
```

**Comment by zah** [comment]
Addressed here:
https://github.com/status-im/nim-eth/pull/24

**Pull request closed without merging**
